#!/bin/bash
set -e

INPUT=$(cat -)

API_KEY="xx"

for TARGET in $INPUT; do

    if [ -f "$TARGET" ]; then
     # since it's a valid file, tell `sha256sum` to read it and hash it:
     HASH=$(sha256sum "$TARGET" | cut --delimiter=' ' --field=1)
    else
      # if it's a string we're precommitting to instead, pipe it into `sha256sum`:
      HASH=$(echo "$TARGET" | sha256sum | cut --delimiter=' ' --field=1)
    fi

     echo -n "$TARGET: "
     curl --request POST --header "Content-Type: application/json" --header "Authorization: Token token=$API_KEY" \
          --data "{\"hash_sha256\":\"$HASH\",\"title\":\"$TARGET\"}" 'http://www.originstamp.org/api/stamps'
     # print newline to keep output tidier since curl doesn't add a final newline to the JSON output
     echo ""
done